apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-ingress-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingress-controller
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
